linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_relative_imports: true
    constant_identifier_names: false
    directives_ordering: true
    use_setters_to_change_properties: false
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    prefer_if_elements_to_conditional_expressions: false
    import_of_legacy_library_into_null_safe: false
    avoid_print: false
    avoid_positional_boolean_parameters: false
