include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true
    prefer_relative_imports: true
    constant_identifier_names: false
    use_setters_to_change_properties: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    prefer_if_elements_to_conditional_expressions: false
    import_of_legacy_library_into_null_safe: false
    avoid_print: false
    avoid_positional_boolean_parameters: false
